codecov:
  require_ci_to_pass: yes

comment:
  layout: "reach, diff, flags, files"
  behaviour: default

coverage:
  status:
    project: 
      default: 
        target: auto
      backend:
        target: auto
        threshold: 5%
        flags:
          - backend
      frontend:
        target: auto
        threshold: 5%
        flags:
          - frontend

    patch:
      default:
        target: 60%

flags:
  backend:
    paths:
      - "backend/**"
    carryforward: yes
  frontend:
    paths:
      - "frontend/**"
    carryforward: yes